kind: Service
apiVersion: v1
metadata:
  name: microservices
spec:
  selector:
    app: microservices
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
  labels:
    app: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices
      tier: backend
  template:
    metadata:
      labels:
        app: microservices
        tier: backend
    spec:
      containers:
      - name: microservices
        image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}   
        ports:
        - name: http
          containerPort: 80
          protocol: TCP